### ISSUE TITLE
请问proto能编译过吗？

### ISSUE THREAD

**Issue by gaojun1146** [LeonDevLifeLog/wildfirechat-proto-docker#1]
请问proto能编译过吗？我在编译的时候一直提示编译有问题；
'info APP_MODULES = sdt'
'export LOCAL_MODULE=comm static jni/../../comm/jni/ jni/../../comm/jni/../  jni/../../comm/jni/../../ jni/../../comm/jni/../../../'
'export LOCAL_MODULE=appcomm static jni/../../app/jni/../ jni/../../app/jni/../src jni/../../app/jni/../interface'
'export LOCAL_MODULE=comm static jni/../../app/jni/../../comm/jni/ jni/../../app/jni/../../comm/jni/../  jni/../../app/jni/../../comm/jni/../../ jni/../../app/jni/../../comm/jni/../../../'
Android NDK: Trying to define local module 'comm' in jni/Android.mk.    
Android NDK: But this module was already defined by jni/Android.mk.    
make: Entering directory `/home/root/WildFireChat/proto-firechat/mars/sdt'
/home/root/android-ndk-r14b/build/core/build-module.mk:34: *** Android NDK: Aborting.    .  Stop.
make: Leaving directory `/home/root/WildFireChat/proto-firechat/mars/sdt'
build static libs fail!!!

**Comment by LeonDevLifeLog** [comment]
可以编译通过,你这用的ndk版本不对,需要用 ndk-r12b
